apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    author: Saidov
  name: nginx2
  namespace: s-35
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
